import Board
import cardDeck

class TokyoBoard(Board.Board):
    def __init__(self):
        super().__init__()
        self.trainLines.append(Board.TrainLine(2,2))
        self.trainLines[0].addStations(self.stations, 11)
        
        self.trainLines.append(Board.TrainLine(2,4))
        self.trainLines[1].addStation(self.trainLines[0].stations[0])
        self.trainLines[1].addStation(self.trainLines[0].stations[1])
        self.trainLines[1].addStation(self.trainLines[0].stations[2])
        self.trainLines[1].addStation(self.trainLines[0].stations[3])
        self.trainLines[1].addStation(self.trainLines[0].stations[4])
        self.trainLines[1].addStation(self.trainLines[0].stations[5])
        self.trainLines[1].addStations(self.stations, 8)
        
        self.trainLines.append(Board.TrainLine(3,7))
        self.trainLines[2].addStations(self.stations, 3)
        self.trainLines[2].addStation(self.trainLines[1].stations[7])
        self.trainLines[2].addStations(self.stations, 10)
        
        self.trainLines.append(Board.TrainLine(3,5))
        self.trainLines[3].addStations(self.stations, 4)
        self.trainLines[3].addStation(self.trainLines[0].stations[8])
        self.trainLines[3].addStations(self.stations, 1)
        self.trainLines[3].addStation(self.trainLines[1].stations[9])
        self.trainLines[3].addStations(self.stations, 3)
        self.trainLines[3].addStation(self.trainLines[2].stations[5])
        self.trainLines[3].addStations(self.stations, 4)
        self.trainLines[3].addStation(self.trainLines[0].stations[5])
        
        self.trainLines.append(Board.TrainLine(3,4))
        self.trainLines[4].addStations(self.stations, 1)
        self.trainLines[4].addStation(self.trainLines[0].stations[9])
        self.trainLines[4].addStations(self.stations, 2)
        self.trainLines[4].addStation(self.trainLines[3].stations[7])
        self.trainLines[4].addStation(self.trainLines[3].stations[8])
        self.trainLines[4].addStation(self.trainLines[1].stations[10])
        self.trainLines[4].addStation(self.trainLines[2].stations[5])
        self.trainLines[4].addStation(self.trainLines[3].stations[11])
        self.trainLines[4].addStations(self.stations, 5)
        
        self.trainLines.append(Board.TrainLine(2,4))
        self.trainLines[5].addStation(self.trainLines[0].stations[10])
        self.trainLines[5].addStation(self.trainLines[4].stations[2])
        self.trainLines[5].addStations(self.stations, 1)
        self.trainLines[5].addStation(self.trainLines[1].stations[9])
        self.trainLines[5].addStation(self.trainLines[2].stations[4])
        self.trainLines[5].addStations(self.stations, 1)
        self.trainLines[5].addStation(self.trainLines[2].stations[5])
        self.trainLines[5].addStations(self.stations, 4)
        
        self.trainLines.append(Board.TrainLine(2,5))
        self.trainLines[6].addStation(self.trainLines[5].stations[0])
        self.trainLines[6].addStation(self.trainLines[5].stations[1])
        self.trainLines[6].addStation(self.trainLines[5].stations[2])
        self.trainLines[6].addStation(self.trainLines[5].stations[3])
        self.trainLines[6].addStation(self.trainLines[3].stations[7])
        self.trainLines[6].addStations(self.stations, 1)
        self.trainLines[6].addStation(self.trainLines[3].stations[9])
        self.trainLines[6].addStation(self.trainLines[2].stations[6])
        self.trainLines[6].addStation(self.trainLines[5].stations[7])
        self.trainLines[6].addStations(self.stations, 4)
        
        self.trainLines.append(Board.TrainLine(3,6))
        self.trainLines[7].addStations(self.stations, 3)
        self.trainLines[7].addStation(self.trainLines[3].stations[8])
        self.trainLines[7].addStation(self.trainLines[1].stations[10])
        self.trainLines[7].addStation(self.trainLines[3].stations[9])
        self.trainLines[7].addStations(self.stations, 2)
        self.trainLines[7].addStation(self.trainLines[2].stations[7])
        self.trainLines[7].addStations(self.stations, 1)
        self.trainLines[7].addStation(self.trainLines[6].stations[9])
        self.trainLines[7].addStation(self.trainLines[6].stations[10])
        self.trainLines[7].addStations(self.stations, 1)
        self.trainLines[7].addStation(self.trainLines[4].stations[12])
        
        self.trainLines.append(Board.TrainLine(3,4))
        self.trainLines[8].addStations(self.stations, 3)
        self.trainLines[8].addStation(self.trainLines[3].stations[7])
        self.trainLines[8].addStation(self.trainLines[3].stations[6])
        self.trainLines[8].addStation(self.trainLines[3].stations[5])
        self.trainLines[8].addStation(self.trainLines[1].stations[8])
        self.trainLines[8].addStation(self.trainLines[1].stations[7])
        self.trainLines[8].addStation(self.trainLines[3].stations[13])
        self.trainLines[8].addStations(self.stations, 4)

def testRoutine():
    tokyoBoardTest = TokyoBoard()
    cardDeckTest = cardDeck.CardDeck()
    print(tokyoBoardTest.getState())
    tokyoBoardTest.makeMove(4, '6')
    tokyoBoardTest.makeMove(5, 'c2')
    tokyoBoardTest.makeMove(5, 's')
    tokyoBoardTest.makeMove(4, '6')
    tokyoBoardTest.makeMove(4, '6')
    print(tokyoBoardTest)
    print(tokyoBoardTest.getState())
    print('Points: '+str(tokyoBoardTest.calculateScore()))
    print(tokyoBoardTest.getValidMoves())
    print(tokyoBoardTest.previewMove(1, '6'))
    print(tokyoBoardTest)
    print(tokyoBoardTest.getState()+cardDeckTest.getState())

testRoutine()
